[colors]
selected_fg = "White"
selected_bg = "Blue"
edit_fg = "White"
edit_bg = "LightBlue"

[layout]
columns = ["Title", "Authors", "id", "???"]

[sorting]
columns = [["authors", false], ["id", true]]

[navigation]
scroll = 5
inverted = false

[database]
file = "rustbreak.db"
