[colors]
selected_fg = "white"
selected_bg = "lightblue"

[layout]
columns = ["Title", "Authors", "ID"]

[sorting]
column = "ID"
reverse = true

[database]
file = "books.db"

[navigation]
scroll = 5
inverted = false