[package]
name = "bookstore-tui"
version = "0.1.0"
authors = ["philippeitis <33013301+philippeitis@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bookstore-app = { version = "0.1.0", path = "../bookstore-app/" }
bookstore-database = { version = "0.1.0", path = "../bookstore-database" }
bookstore-records = { version = "0.1.0", path = "../bookstore-records" }

clap = "3.0.0-beta.2"
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
unicode-truncate = "0.2.0"
crossterm = "0.19.0"
html2text = "0.2.1"
