name: Rust

on:
  push:
    paths:
    - "**/*.rs"
    - "**/*.yml"
    - "**/*.toml"
  pull_request:
    paths:
    - "**/*.rs"
    - "**/*.yml"
    - "**/*.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cd bookstore && cargo test --verbose
  fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - name: Formatting
      run: rustup component add rustfmt && cd bookstore && cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - name: Run clippy
      run: rustup component add clippy && cd bookstore && cargo clippy
