name: Rust

on:
  push:
    paths:
    - "**/*.rs"
  pull_request:
    paths:
    - "**/*.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd bookstore && cargo build --verbose
    - name: Run tests
      run: cd bookstore && cargo test --verbose
